name: Docs
description: Documentation missing, wrong, or outdated
title: "[Docs]: "
type: Docs
labels: ["needs-triage"]
projects: ["FleetCore"]
body:
  - type: input
    id: link
    attributes:
      label: Documentation URL
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
    validations:
      required: true